### ISSUE TITLE
you don't have the required permission to change your wheel settings

### ISSUE THREAD

**Issue by sayapinsergej** [berarma/oversteer#106]
Hello! Thank you for your project! How to fix the error?

**Comment by berarma** [comment]
I need more details about how you installed Oversteer and the wheel you're using.

**Comment by sayapinsergej** [comment]
pi@raspberrypi:~/Downloads/oversteer-master $ meson build
The Meson build system
Version: 0.56.1
Source dir: /home/pi/Downloads/oversteer-master
Build dir: /home/pi/Downloads/oversteer-master/build
Build type: native build
Project name: oversteer
Project version: 0.7.1
Host machine cpu family: arm
Host machine cpu: armv6l
Program python3 found: YES (/usr/bin/python3)
Configuring org.berarma.Oversteer.desktop.tmp using configuration
Program appstream-util found: YES (/usr/bin/appstream-util)
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Configuring oversteer using configuration
Program scripts/meson_post_install.py found: YES (/usr/bin/python3 /home/pi/Downloads/oversteer-master/scripts/meson_post_install.py)
Build targets in project: 7

Found ninja-1.10.1 at /usr/bin/ninja
pi@raspberrypi:~/Downloads/oversteer-master $ cd build
pi@raspberrypi:~/Downloads/oversteer-master/build $ ninja install
[2/3] Installing files.
Installing subdir /home/pi/Downloads/oversteer-master/oversteer to /usr/lib/python3.7/site-packages/oversteer
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
Installing subdir /home/pi/Downloads/oversteer-master/oversteer to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/device_manager.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/signal.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/wheel_ids.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/model.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/combined_chart.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/gui.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/linear_chart.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/test.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/gtk_handlers.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/gtk_ui.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/__init__.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/device.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/performance_chart.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/application.py to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/main.ui to /usr/lib/python3.7/site-packages/oversteer
Installing /home/pi/Downloads/oversteer-master/oversteer/main.css to /usr/lib/python3.7/site-packages/oversteer
Installing subdir /home/pi/Downloads/oversteer-master/data/udev to /usr/local/lib/udev/rules.d
Installing /home/pi/Downloads/oversteer-master/data/udev/99-logitech-wheel-perms.rules to /usr/local/lib/udev/rules.d
Installing /home/pi/Downloads/oversteer-master/data/udev/99-thrustmaster-wheel-perms.rules to /usr/local/lib/udev/rules.d
Installing /home/pi/Downloads/oversteer-master/data/udev/99-fanatec-wheel-perms.rules to /usr/local/lib/udev/rules.d
Installing data/org.berarma.Oversteer.desktop to /usr/local/share/applications
Installing data/org.berarma.Oversteer.appdata.xml to /usr/local/share/metainfo
Installing /home/pi/Downloads/oversteer-master/data/org.berarma.Oversteer.svg to /usr/local/share/icons/hicolor/scalable/apps
Installing /home/pi/Downloads/oversteer-master/build/bin/oversteer to /usr/local/bin
Running custom install script '/usr/bin/meson --internal gettext install --r=po --localedir=share/locale --pkgname=oversteer'
Installing /home/pi/Downloads/oversteer-master/build/po/ca.gmo to /usr/local/share/locale/ca/LC_MESSAGES/oversteer.mo
Installing /home/pi/Downloads/oversteer-master/build/po/es.gmo to /usr/local/share/locale/es/LC_MESSAGES/oversteer.mo
Installing /home/pi/Downloads/oversteer-master/build/po/gl.gmo to /usr/local/share/locale/gl/LC_MESSAGES/oversteer.mo
Installing /home/pi/Downloads/oversteer-master/build/po/ru.gmo to /usr/local/share/locale/ru/LC_MESSAGES/oversteer.mo
Installing /home/pi/Downloads/oversteer-master/build/po/fi.gmo to /usr/local/share/locale/fi/LC_MESSAGES/oversteer.mo
Installing /home/pi/Downloads/oversteer-master/build/po/tr.gmo to /usr/local/share/locale/tr/LC_MESSAGES/oversteer.mo
Installing /home/pi/Downloads/oversteer-master/build/po/de.gmo to /usr/local/share/locale/de/LC_MESSAGES/oversteer.mo
Running custom install script '/usr/bin/python3 /home/pi/Downloads/oversteer-master/scripts/meson_post_install.py'
Updating icon cache...
Updating desktop database...
Compiling python bytecode...
Listing '/usr/lib/python3.7/site-packages/oversteer'...
pi@raspberrypi:~/Downloads/oversteer-master/build $

**Comment by sayapinsergej** [comment]
maybe this is the reason?
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...

**Comment by berarma** [comment]
> maybe this is the reason? Installation failed due to insufficient permissions. Attempting to use polkit to gain elevated privileges...

Probably. It should have asked for an administrator password.

Could you check the contents of `/usr/local/lib/udev/rules.d`?

It should contain:

99-logitech-wheel-perms.rules
99-thrustmaster-wheel-perms.rules
99-fanatec-wheel-perms.rules

**Comment by sayapinsergej** [comment]
The administrator password was requested. the contents in /usr/local/lib/udev/rules.d are. What other solutions are there?

**Comment by sayapinsergej** [comment]
the driver is installed. Steering wheel T300RS. In the oversteer program, the test passes, force feedback is also there

**Comment by berarma** [comment]
> the driver is installed. Steering wheel T300RS. In the oversteer program, the test passes, force feedback is also there

Are you using hid-tmff2?

**Comment by sayapinsergej** [comment]
yes

**Comment by berarma** [comment]
Have you restarted your computer?

Please, paste the contents of your thrustmaster file in the /usr/local/share/udev dir.

**Comment by sayapinsergej** [comment]
P.S. Yes,  the computer was restarting

**Comment by berarma** [comment]
You could try copying ```/usr/local/lib/udev/rules.d/99-thrustmaster-wheel-perms.rules``` to ```/lib/udev/rules.d/``` and rebooting.

**Comment by sayapinsergej** [comment]
I'm sorry but I didn't understand where to copy it. To /lib/udev/rules.d/?

**Comment by sayapinsergej** [comment]
![image](https://user-images.githubusercontent.com/107651826/175111498-51bb301e-98ea-4eba-b622-b947b6c7cf9b.jpeg)

**Comment by sayapinsergej** [comment]
![image](https://user-images.githubusercontent.com/107651826/175111701-5b5374c8-4d3a-426f-aed1-28ad7bfd1422.jpeg)

**Comment by fuzunspm** [comment]
I have the same issue. I followed all the instructions, re-installed both oversteer and hid-tmff2 but still having the permission error. It works fine if i run oversteer as root. It was working fine for my old G29 wheel, recently I replaced it for t300 and not I'm having the issue

**Comment by berarma** [comment]
> I have the same issue. I followed all the instructions, re-installed both oversteer and hid-tmff2 but still having the permission error. It works fine if i run oversteer as root. It was working fine for my old G29 wheel, recently I replaced it for t300 and now I'm having the issue

Please, run `oversteer --debug` from the console and paste here the output. Also, paste the output of the lsusb command.

**Comment by fuzunspm** [comment]
```
DEBUG:root:update_device_list: input-pci-0000_01_00_0-usb-0_1_1_0
DEBUG:root:update_device_list: input-pci-0000_01_00_0-usb-0_1_1_0
DEBUG:root:update_device_list: input-pci-0000_01_00_0-usb-0_1_1_0
DEBUG:root:Devices: {'input-pci-0000_01_00_0-usb-0_1_1_0': <oversteer.device.Device object at 0x7f60ecb7feb0>}
DEBUG:matplotlib:matplotlib data path: /usr/lib/python3.10/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/username/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:loaded modules: ['sys', 'builtins', '_frozen_importlib', '_imp', '_thread', '_warnings', '_weakref', '_io', 'marshal', 'posix', '_frozen_importlib_external', 'time', 'zipimport', '_codecs', 'codecs', 'encodings.aliases', 'encodings', 'encodings.utf_8', '_signal', '_abc', 'abc', 'io', '__main__', '_stat', 'stat', '_collections_abc', 'genericpath', 'posixpath', 'os.path', 'os', '_sitebuiltins', '_distutils_hack', 'types', 'importlib._bootstrap', 'importlib._bootstrap_external', 'warnings', 'importlib', 'importlib._abc', 'itertools', 'keyword', '_operator', 'operator', 'reprlib', '_collections', 'collections', '_functools', 'functools', 'contextlib', 'importlib.util', 'importlib.machinery', 'mpl_toolkits', 'ruamel', 'sphinxcontrib', 'site', 'enum', 'signal', '_sre', 'sre_constants', 'sre_parse', 'sre_compile', '_locale', 'copyreg', 're', 'locale', 'oversteer', 'gettext', 'argparse', 'token', 'tokenize', 'linecache', 'traceback', '_weakrefset', 'weakref', 'collections.abc', '_string', 'string', 'threading', 'atexit', 'logging', 'errno', 'fcntl', '_posixsubprocess', 'select', 'math', 'selectors', 'subprocess', '__future__', '_struct', 'struct', 'six', 'pyudev._errors', '_datetime', 'datetime', 'six.moves', 'pyudev._util', 'pyudev.device._device', 'pyudev.device', 'pyudev.discover', '_ctypes', 'ctypes._endian', 'ctypes', 'pyudev._ctypeslib._errorcheckers', 'pyudev._ctypeslib.libc', 'pyudev._ctypeslib.libudev', 'pyudev._ctypeslib', 'fnmatch', 'zlib', '_compression', '_bz2', 'bz2', '_lzma', 'lzma', 'shutil', '_bisect', 'bisect', '_random', '_sha512', 'random', 'tempfile', 'ctypes.util', 'pyudev._ctypeslib.utils', 'pyudev.core', 'pyudev._os.pipe', 'pyudev._os.poll', 'pyudev._os', 'pyudev.monitor', 'pyudev.version', 'pyudev', 'evdev._input', '_ast', 'ast', '_opcode', 'opcode', 'dis', 'inspect', 'evdev._ecodes', 'evdev.ecodes', 'glob', 'evdev.events', 'evdev.util', 'concurrent', 'concurrent.futures._base', 'concurrent.futures', '_heapq', 'heapq', '_socket', 'array', 'socket', '_ssl', 'binascii', 'base64', 'ssl', 'asyncio.constants', 'asyncio.format_helpers', 'asyncio.base_futures', 'asyncio.log', 'asyncio.coroutines', '_contextvars', 'contextvars', 'asyncio.exceptions', 'asyncio.base_tasks', '_asyncio', 'asyncio.events', 'asyncio.futures', 'asyncio.protocols', 'asyncio.transports', 'asyncio.sslproto', 'typing.io', 'typing.re', 'typing', 'asyncio.mixins', 'asyncio.tasks', 'asyncio.locks', 'asyncio.staggered', 'asyncio.trsock', 'asyncio.base_events', 'asyncio.runners', 'asyncio.queues', 'asyncio.streams', 'asyncio.subprocess', 'asyncio.threads', 'asyncio.base_subprocess', 'asyncio.selector_events', 'asyncio.unix_events', 'asyncio', 'evdev._uinput', 'evdev.eventio', 'evdev.eventio_async', 'evdev.device', 'evdev.ff', 'evdev.uinput', 'evdev', 'oversteer.wheel_ids', 'oversteer.device', 'oversteer.device_manager', 'configparser', 'oversteer.model', 'xdg', 'xdg.BaseDirectory', 'oversteer.application', 'oversteer.gui', '_csv', 'csv', 'pkgutil', 'gi._error', 'gi._gi', 'gi._gobject', 'cairo._cairo', 'cairo', 'gi._gi_cairo', 'glib', 'gobject', 'gio', 'gtk', 'gtk.gdk', 'gi', 'gi._constants', 'gi.docstring', 'gi._propertyhelper', 'gi._signalhelper', 'gi.types', 'gi.module', 'gi.overrides', 'gi.importer', 'gi.repository', 'gi.repository.xlib', 'gi.repository.cairo', 'gi.repository.freetype2', 'gi._ossighelper', 'textwrap', 'optparse', 'gi._option', 'gi.overrides.GLib', 'gi.repository.GLib', 'gi.overrides.GObject', 'gi.repository.GObject', 'gi.repository.HarfBuzz', 'gi.overrides.Gio', 'gi.repository.Gio', 'gi.overrides.Pango', 'gi.repository.Pango', 'gi.repository.GModule', 'gi.overrides.GdkPixbuf', 'gi.repository.GdkPixbuf', 'gi.repository.GdkX11', 'gi.overrides.Gdk', 'gi.repository.Gdk', 'gi.repository.Atk', 'gi._gtktemplate', 'gi.overrides.Gtk', 'gi.repository.Gtk', 'oversteer.gtk_handlers', 'oversteer.gtk_ui', 'numpy._globals', 'numpy.__config__', 'numpy._distributor_init', '_json', 'json.scanner', 'json.decoder', 'json.encoder', 'json', 'numpy._version', 'numpy.version', 'numpy.core._multiarray_umath', 'numpy.compat._inspect', 'numpy.compat._pep440', 'ntpath', 'urllib', 'urllib.parse', 'pathlib', '_compat_pickle', '_pickle', 'pickle', 'numpy.compat.py3k', 'numpy.compat', 'numpy.core.overrides', 'numpy.core.multiarray', 'numpy.core.umath', 'numbers', 'numpy.core._string_helpers', 'numpy.core._dtype', 'numpy.core._type_aliases', 'numpy.core.numerictypes', 'numpy.core._exceptions', 'numpy.core._methods', 'numpy.core.fromnumeric', 'numpy.core.shape_base', 'numpy.core._ufunc_config', 'numpy.core.arrayprint', 'numpy.core._asarray', 'numpy.core.numeric', 'numpy.core.defchararray', 'numpy.core.records', 'numpy.core.memmap', 'numpy.core.function_base', 'numpy.core._machar', 'numpy.core.getlimits', 'numpy.core.einsumfunc', 'numpy.core._multiarray_tests', 'numpy.core._add_newdocs', 'platform', 'numpy.core._add_newdocs_scalars', 'numpy.core._dtype_ctypes', 'numpy.core._internal', 'numpy._pytesttester', 'numpy.core', 'numpy.lib.mixins', 'numpy.lib.ufunclike', 'numpy.lib.type_check', 'numpy.lib.scimath', 'numpy.lib.stride_tricks', 'numpy.lib.twodim_base', 'numpy.linalg._umath_linalg', 'numpy.linalg.linalg', 'numpy.linalg', 'numpy.matrixlib.defmatrix', 'numpy.matrixlib', 'numpy.lib.histograms', 'numpy.lib.function_base', 'numpy.lib.index_tricks', 'numpy.lib.nanfunctions', 'numpy.lib.shape_base', 'numpy.lib.polynomial', 'numpy.lib.utils', 'numpy.lib.arraysetops', 'numpy.lib.format', 'numpy.lib._datasource', 'numpy.lib._iotools', 'numpy.lib.npyio', 'numpy.lib.arrayterator', 'numpy.lib.arraypad', 'numpy.lib._version', 'numpy.lib', 'numpy.fft._pocketfft_internal', 'numpy.fft._pocketfft', 'numpy.fft.helper', 'numpy.fft', 'numpy.polynomial.polyutils', 'numpy.polynomial._polybase', 'numpy.polynomial.polynomial', 'numpy.polynomial.chebyshev', 'numpy.polynomial.legendre', 'numpy.polynomial.hermite', 'numpy.polynomial.hermite_e', 'numpy.polynomial.laguerre', 'numpy.polynomial', 'cython_runtime', '_cython_0_29_30', 'numpy.random._common', '_hashlib', '_blake2', 'hashlib', 'hmac', 'secrets', 'numpy.random.bit_generator', 'numpy.random._bounded_integers', 'numpy.random._mt19937', 'numpy.random.mtrand', 'numpy.random._philox', 'numpy.random._pcg64', 'numpy.random._sfc64', 'numpy.random._generator', 'numpy.random._pickle', 'numpy.random', 'numpy.ctypeslib', 'numpy.ma.core', 'numpy.ma.extras', 'numpy.ma', 'numpy', 'oversteer.test', 'oversteer.combined_chart', 'matplotlib', 'copy', 'dataclasses', 'pprint', 'packaging.__about__', 'packaging', 'packaging._structures', 'packaging.version', 'matplotlib._api.deprecation', 'matplotlib._api', 'matplotlib._version', 'gzip', 'shlex', 'matplotlib._c_internal_utils', 'matplotlib.cbook', 'matplotlib.docstring', 'PIL._version', 'PIL', 'PIL.ImageMode', 'PIL.TiffTags', 'PIL._binary', 'PIL._deprecate', 'PIL._util', 'PIL._imaging', 'cffi.lock', 'cffi.error', 'cffi.model', 'cffi.api', 'cffi', 'PIL.Image', 'PIL.ImageChops', 'PIL.ImageFile', 'PIL.GimpGradientFile', 'PIL.GimpPaletteFile', 'PIL.ImageColor', 'PIL.PaletteFile', 'PIL.ImagePalette', 'PIL.ImageSequence', 'PIL.PngImagePlugin', 'matplotlib._path', 'matplotlib.bezier', 'matplotlib.path', 'matplotlib.transforms', 'matplotlib.ticker', 'matplotlib.scale', 'matplotlib._color_data', 'matplotlib.colors', 'pyparsing.util', 'pyparsing.unicode', 'pyparsing.exceptions', 'pyparsing.actions', 'pyparsing.results', 'pyparsing.core', 'html.entities', 'html', 'pyparsing.helpers', 'pyparsing.testing', 'pyparsing.common', 'pyparsing', 'matplotlib.fontconfig_pattern', 'matplotlib._enums', 'cycler', 'matplotlib.rcsetup', 'matplotlib.ft2font', 'dateutil._version', 'dateutil', 'kiwisolver._cext', 'kiwisolver']
DEBUG:matplotlib:CACHEDIR=/home/username/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/username/.cache/matplotlib/fontlist-v330.json
```

```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 1532:005c Razer USA, Ltd DeathAdder Elite
Bus 003 Device 002: ID 0951:16e5 Kingston Technology HyperX Alloy Origins
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 007: ID 1e71:1714 NZXT Smart Device
Bus 001 Device 006: ID 045e:00cb Microsoft Corp. Basic Optical Mouse v2.0
Bus 001 Device 005: ID 1e71:170e NZXT Kraken X
Bus 001 Device 004: ID 0bda:8771 Realtek Semiconductor Corp. Bluetooth Radio
Bus 001 Device 003: ID 046d:082d Logitech, Inc. HD Pro Webcam C920
Bus 001 Device 008: ID 046d:c31c Logitech, Inc. Keyboard K120
Bus 001 Device 009: ID 044f:b66e ThrustMaster, Inc. Thrustmaster T300RS Racing wheel
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by berarma** [comment]
I guess you've already tried everything in the messages above. If that's the case I don't know why it doesn't work. Maybe udev isn't working correctly. Which distro are you using?

**Comment by fuzunspm** [comment]
I'm on arch linux, my old g29 is working

**Comment by berarma** [comment]
Can you try pasting this line at the end of `/usr/local/lib/udev/rules.d/99-thrustmaster-wheel-perms.rules` and rebooting:
`SUBSYSTEMS=="hid", KERNELS=="0003:044F:B66E.????", RUN+="/bin/sh -c 'cd %S%p/../../../; chmod 666 range spring_level damper_level friction_level alternate_modes'"`

**Comment by fuzunspm** [comment]
I'm still getting the same error but this time I can actually change wheel settings

**Comment by detrophy** [comment]
I also got this issue. Fresh install of Manjaro with a current image.
hid-tmff2 is installed, DKMS mode
T300 RS GT is the wheel

**Comment by berarma** [comment]
I've added debug info to help identify the issue. Please, update to the latest master commit, install and run `oversteer --debug` from the terminal, then paste the output here. Thanks.

**Comment by detrophy** [comment]
`
DEBUG:root:update_device_list: input-pci-0000_02_00_0-usb-0_4_1_0
DEBUG:root:update_device_list: input-pci-0000_02_00_0-usb-0_4_1_0
DEBUG:root:update_device_list: input-pci-0000_02_00_0-usb-0_4_1_0
DEBUG:root:Devices: {'input-pci-0000_02_00_0-usb-0_4_1_0': <oversteer.device.Device object at 0x7f5062e0b940>}
DEBUG:matplotlib:matplotlib data path: /usr/lib/python3.10/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/detrophy/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
... loading modules part ...
DEBUG:matplotlib:CACHEDIR=/home/detrophy/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/detrophy/.cache/matplotlib/fontlist-v330.json
DEBUG:root:chech_permissions: /sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4:1.0/0003:044F:B66E.0011
DEBUG:root:check_file_permissions mode: 0o666 user: root group: root file: /sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4:1.0/0003:044F:B66E.0011/alternate_modes
DEBUG:root:check_file_permissions mode: 0o666 user: root group: root file: /sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4:1.0/0003:044F:B66E.0011/range
DEBUG:root:check_file_permissions mode: 0o644 user: root group: root file: /sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4:1.0/0003:044F:B66E.0011/gain
`

**Comment by berarma** [comment]
It should be fixed in the master branch. Please test.

**Comment by fuzunspm** [comment]
thank you! my package manager don't have the update yet but manually editing udev rules file fixed the issue on my end

**Comment by berarma** [comment]
> thank you! my package manager don't have the update yet but manually editing udev rules file fixed the issue on my end

Thanks!

**Comment by dbPietah** [comment]
~~Still an issue in 0.8.3 I'm afraid, installed using flatpak. I don't have any rules in udev concerning steering wheels.~~

Never mind, I installed it from the software center and thus hadn't seen the additional steps 😊 
 
- Thrustmaster  T300 RS GT is the wheel
- OS: Zorin OS 18.1 x86_64 
- Kernel: 7.0.0-31-generic 
- hid-tmff2 is installed, DKMS mode
